### ISSUE TITLE
Demo Directions Incomplete

### ISSUE THREAD

**Issue by jmbrewer** [shihyuntang/igrins_rv#5]
The 'Demo for IGRINS RV' directions have a few typos and are missing some steps.

We are told to 'Simply move igrins_rv/Example/GJ281 to ./igrins_rv-master/input/'.  The input directory is 'Input' and it was a little confusing that the master directory was referenced differently (at all really) from one part of the sentence to the next.

The next step is 'All users now move Prepdata_A0_GJ281.txt and Prepdata_targ_GJ281.txt to ./igrins_rv-master/input/Prepdata/' but it was unclear (without searching through the directories) where these files were for the demo data if we had not run plp.

**Comment by shihyuntang** [comment]
Hi @jmbrewer ,

Yes, it was confusing. Thank you for spotting this.
I changed this section to:
![スクリーンショット 2021-04-11 12 53 02](https://user-images.githubusercontent.com/26864783/114319133-fcc57a80-9ac4-11eb-9db4-2c6f9aaaac21.png)
