### ISSUE TITLE
JOSS Review Notes 2

### ISSUE THREAD

**Issue by jmbrewer** [shihyuntang/igrins_rv#6]
Hello,
I am going to follow @gully's example and introduce myself as the second JOSS reviewer.  It seemed a good idea to keep my notes in a separate thread.  I will try not to repeat issues that he has already mentioned.

## Initial Impressions
The authors state that the code has only been tested on Linux and with a limited selection of gcc/gfortran compilers (for the TelFit dependency).  I am **installing on a Mac (Core i7 with OS 10.15.7)** and had several issues in getting the proper Fortran, but eventually hit upon the right combo.

### MESA SDK gfortran (doesn't work)
I have previously installed the MESA-SDK which has gfortran 9.x.x.  The igrins RV documentation made it sound as though this might be OK (specifies: 'cannot not work under versions later than v9.X.X').  The error that I got was *similar to* the 'Known Bug' mentioned but a bit earlier.  After attempting for a while, making various modifications I gave up.

### Homebrew gcc@7
I used homebrew to install gcc@7 (v 7.5.x) and then creating symlinks for `ln -s /usr/local/bin/gcc-7 gcc` and `ln -s /usr/local/bin/gfortran-7 /usr/local/bin/gfortran` I was able to install using the instructions.  I did encounter the 'Known Bug' and fell that this needs to move up in the directions or some other method for patching the code may be preferable to where it is now.  Since I had already tried multiple times I understood what I needed to do, but the first time installer may waste some time in tracking this down.  Also, I encountered the bug in 'build' and not 'install', so reran build before running install.

### Step 1 running
After figuring out where the Prepdata was (posted as separate issue) I was able to run Step 1.  Still running, but seems fine so far.

**Comment by jmbrewer** [comment]
## Step 2
It was nice to have the input parameters displayed for confirmation before the run started.  However, the highlighting method used made them unreadable in my terminal.  It may be better to choose some other emphasis indicator or change both the font and the background color so that you ensure readability.

**Comment by jmbrewer** [comment]
## Step 3
Some of the plots have a strange break in them that I wasn't sure was intentional:
![parfit_5_20170911_0119](https://user-images.githubusercontent.com/8174989/114206835-95ff6000-9910-11eb-9125-8d52af8bec49.png)
I assume that this is two different orders, but the thin vertical dashed line doesn't make it all that clear, especially in cases where the continuum levels are roughly the same in both.

[edit] After thinking about it for a bit I realize that this can't be two orders because the levels are well matched, so now I am less sure of the reason for the break.

**Comment by jmbrewer** [comment]
I am curious about the continuum fitting, although it may not matter much for deriving the RVs.  This plot and others show a notch that seems unphysical.  Is this a problem in the fitting or is there some detector reason for the notch?
 
![parfit_6_20170910_0102](https://user-images.githubusercontent.com/8174989/114207590-63099c00-9911-11eb-80df-0ce828549642.png)

**Comment by shihyuntang** [comment]
> ## Step 3
> Some of the plots have a strange break in them that I wasn't sure was intentional:
> ![parfit_5_20170911_0119](https://user-images.githubusercontent.com/8174989/114206835-95ff6000-9910-11eb-9125-8d52af8bec49.png)

Hi @jmbrewer , yes, this is intentional, but not for showing different orders. 
Because we do not use the whole wavelength region in some of the orders for fitting, we mask the skipped wavelength by this break on plots.
Here is table 3 from our AJ paper that just been accepted ([Stahl et al. 2021](https://ui.adsabs.harvard.edu/abs/2021arXiv210402082S/abstract)) showing the cut in individual order:
![スクリーンショット 2021-04-09 8 56 12](https://user-images.githubusercontent.com/26864783/114207743-91877700-9911-11eb-80f7-588ecf8cc953.png)

**Comment by shihyuntang** [comment]
> I am curious about the continuum fitting, although it may not matter much for deriving the RVs. This plot and others show a notch that seems unphysical. Is this a problem in the fitting or is there some detector reason for the notch?
> 
> ![parfit_6_20170910_0102](https://user-images.githubusercontent.com/8174989/114207590-63099c00-9911-11eb-80df-0ce828549642.png)

Yes! you are correct. This is a combination of issue from the instrument + 1D spectra reduction pipeline as described in Section 2.2. and Figure 3 our the AJ paper. The unphysical bucket (as how we call it internally) is the result of us trying to model that effect.

**Comment by shihyuntang** [comment]
Hi @jmbrewer ,

Thank you for your great comments and the help finding the right combo to let `Telfit` running on MacOS!
Here are my responds to all your comments posted here:

For **Initial Impressions**: It looks like gfortran version 7.X.X is best to work with `Telfit`. I am able to make `Telfit` run under MacOS v11.2.3 and v10.15.7 with brew install gcc@7. I have updated the statement in the installation pager now with: 
> NOTE:The current versions (v0.9.X) of IGRINS RV has only been tested on Linux and MacOS...

I also updated the FAQ page to guide the user on installing gfortran v7.X.X.

For **Step 2**: Now adding the ANSI code to force the font color to white. Thank you for spotting this.

For **Step 3**: As I replied above.

All changes can be found on the `JOSS_review_updates` branch.

**Comment by jmbrewer** [comment]
Is there documentation on the pipeline options other than the example and the individual --help for the steps?  I can't seem to find it.

**Comment by shihyuntang** [comment]
Hi @jmbrewer ,

Explanation on the pipeline input options can also be found on the wiki page under each step's page, e.g., for step3 see the [keyword](https://github.com/shihyuntang/igrins_rv/wiki/Step-3:-Full-Analysis#keywords) section.

**Comment by shihyuntang** [comment]
Dear @jmbrewer ,

I hope my reply answered your question, if not, please let me know.
Also, is there anything else that you wish us to improve to meet the requirement for the unchecked box in the JOSS REVIEW [issue page](https://github.com/openjournals/joss-reviews/issues/3095#issue-828126538)?

Thank you.
